//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✔ Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ч..
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Попытка изменить несуществующее свойство сущности БД!.
        /// </summary>
        public static string messageErrorPropertyNotExist {
            get {
                return ResourceManager.GetString("messageErrorPropertyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Тип аргумента не соответствует заданному значению при попытке изменения свойства сущности БД!.
        /// </summary>
        public static string messageErrorPropertyValueType {
            get {
                return ResourceManager.GetString("messageErrorPropertyValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📋 Имя задачи:.
        /// </summary>
        public static string tableTaskAnnotation1 {
            get {
                return ResourceManager.GetString("tableTaskAnnotation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🕮 Описание:.
        /// </summary>
        public static string tableTaskAnnotation2 {
            get {
                return ResourceManager.GetString("tableTaskAnnotation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📅 Создана:.
        /// </summary>
        public static string tableTaskAnnotation3 {
            get {
                return ResourceManager.GetString("tableTaskAnnotation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⌚ Срок выполнение, ч:.
        /// </summary>
        public static string tableTaskAnnotation4 {
            get {
                return ResourceManager.GetString("tableTaskAnnotation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⏳ Затрачено, ч:.
        /// </summary>
        public static string tableTaskAnnotation5 {
            get {
                return ResourceManager.GetString("tableTaskAnnotation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 👥 Исполнители:.
        /// </summary>
        public static string tableTaskAnnotation6 {
            get {
                return ResourceManager.GetString("tableTaskAnnotation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на + 👤 Добавить исполнителя:.
        /// </summary>
        public static string tableTaskAnnotation7 {
            get {
                return ResourceManager.GetString("tableTaskAnnotation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🏁 Дата завершения:.
        /// </summary>
        public static string tableTaskAnnotation8 {
            get {
                return ResourceManager.GetString("tableTaskAnnotation8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ♔ Статус:.
        /// </summary>
        public static string TableTaskStatus {
            get {
                return ResourceManager.GetString("TableTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая задача.
        /// </summary>
        public static string taskNewName {
            get {
                return ResourceManager.GetString("taskNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ☝ Назначена.
        /// </summary>
        public static string taskStatus0 {
            get {
                return ResourceManager.GetString("taskStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ▶  Выполняется.
        /// </summary>
        public static string taskStatus1 {
            get {
                return ResourceManager.GetString("taskStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⏸ Приостоновлена.
        /// </summary>
        public static string taskStatus2 {
            get {
                return ResourceManager.GetString("taskStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🏁 Завершена.
        /// </summary>
        public static string taskStatus3 {
            get {
                return ResourceManager.GetString("taskStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка!.
        /// </summary>
        public static string titleError {
            get {
                return ResourceManager.GetString("titleError", resourceCulture);
            }
        }
    }
}
